# Licensed under the Apache License, Version 2.0 (see LICENSE).

[GLOBAL]
pants_version = "1.29.0"
v1 =  false  # Turn off the v1 execution engine.
v2 = true  # Enable the v2 execution engine.
dynamic_ui = false
enable_pantsd = false  # Enable the Pants daemon for better performance.

backend_packages = []  # Deregister all v1 backends.

# List v2 backends here.
backend_packages2.add = [
  'pants.backend.python',
#  'pants.backend.python.lint.docformatter',  # fails on dtab/__init__.py
  'pants.backend.python.lint.black',
  'pants.backend.python.lint.flake8',
  'pants.backend.python.lint.isort',
]

# List v2 plugins here.
plugins2 = []

[source]
# The Python source root is the repo root. See https://pants.readme.io/docs/source-roots.
root_patterns = ["/"]

[python-setup]
# The default interpreter compatibility for code in this repo. Individual targets can override
#  this with the `compatibility` field. See
#  https://pants.readme.io/docs/python-interpreter-compatibility.
interpreter_constraints = [">=3.6"]
# Use a lockfile. See https://pants.readme.io/docs/python-third-party-dependencies.
requirement_constraints = "constraints.txt"

[flake8]
config = ".flake8"

[isort]
config = [".isort.cfg"]
