VERSION = '0.0.1'

python_library(name='dtab',
  sources=['*.py'],
  provides=setup_py(
    name='python-dtab',
    version=VERSION,
    description='Python DTab Parser',
    long_description="""A Python port of Finagle's DTab Parser (Delegation Table) library.""",
    url='https://github.com/JustinVenus/python-dtab',
    license='Apache License, Version 2.0',
    zip_safe=True,
    classifiers=[
      'Intended Audience :: Developers',
      'License :: OSI Approved :: Apache Software License',
      'Operating System :: MacOS :: MacOS X',
      'Operating System :: POSIX :: Linux',
      'Programming Language :: Python',
    ]
  )
)
